# Generated by Django 4.2.3 on 2023-07-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_user',
            new_name='id_usuario',
        ),
    ]
